version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: pg_local
    environment:
      POSTGRES_USER: sunnylee
      POSTGRES_PASSWORD: l890226
      POSTGRES_DB: image_db
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_local
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: always

volumes:
  pg_data:
  qdrant_data: 